# Generated by cargorewind: environment at base commit e776ff0000000000000000000000000000000000.
FROM rust:1.73.0-slim@sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff AS toolchain
LABEL project=cargorewind \
      cargorewind.base-commit=e776ff0000000000000000000000000000000000 \
      cargorewind.toolchain=1.73.0
ENV CARGO_BUILD_JOBS=2 \
    CARGO_INCREMENTAL=0 \
    CARGO_TERM_COLOR=never \
    CARGO_TARGET_DIR=/home/rewind/target
RUN useradd --create-home --uid 10001 rewind
USER rewind
WORKDIR /home/rewind/repo
COPY --chown=rewind:rewind repo/ ./

FROM toolchain
# Sanity probe: the identifiers the patches add must not exist at the base commit.
RUN grep -rlwF --include='*.rs' \
        -e check_name \
        . ; \
    test $? -eq 1 || { echo "cargorewind probe failed: found at base (files above)" >&2; exit 1; }
# Cargo.lock written by cargorewind: every crates.io package was published
# before 2023-10-17T21:35:00+00:00 (see lock.json).
COPY --chown=rewind:rewind Cargo.lock ./
RUN cargo fetch --locked
# Vendor every dependency and point cargo at the copies; tests run --offline.
RUN mkdir -p /home/rewind/.cargo \
    && cargo vendor --locked /home/rewind/vendor > /home/rewind/.cargo/config.toml
ENV CARGO_NET_OFFLINE=true
# Warm build: compile dependencies and every test target once at base.
RUN cargo test --no-run --offline
# Recipe hash: sha256 of the canonical recipe JSON (recipe.json) and of the lines
# above; the build cache key.
LABEL cargorewind.recipe=dadcac438dc99cb93b2892872ca820e93bc3d8beda0956d835748ec294bb75d6
