# Generated by cargorewind: environment at base commit e776ff0000000000000000000000000000000000.
FROM rust:1.73.0-slim@sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff AS toolchain
LABEL project=cargorewind \
      cargorewind.base-commit=e776ff0000000000000000000000000000000000 \
      cargorewind.toolchain=1.73.0
ENV CARGO_BUILD_JOBS=2 \
    CARGO_INCREMENTAL=0 \
    CARGO_TERM_COLOR=never \
    CARGO_TARGET_DIR=/home/rewind/target
RUN useradd --create-home --uid 10001 rewind
USER rewind
WORKDIR /home/rewind/repo
COPY --chown=rewind:rewind repo/ ./
