# Generated by cargorewind: environment at base commit 0123456789abcdef0123456789abcdef01234567.
FROM rust:1.70.0-slim@sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
LABEL project=cargorewind \
      cargorewind.base-commit=0123456789abcdef0123456789abcdef01234567 \
      cargorewind.toolchain=1.70.0
ENV CARGO_BUILD_JOBS=2 \
    CARGO_INCREMENTAL=0 \
    CARGO_TERM_COLOR=never \
    CARGO_TARGET_DIR=/home/rewind/target
# Components and targets the toolchain file asks for.
RUN rustup component add --toolchain 1.70.0 clippy rustfmt \
    && rustup target add --toolchain 1.70.0 wasm32-unknown-unknown
# Pin the chosen toolchain; rustup would otherwise follow the toolchain file.
ENV RUSTUP_TOOLCHAIN=1.70.0
RUN useradd --create-home --uid 10001 rewind
USER rewind
WORKDIR /home/rewind/repo
COPY --chown=rewind:rewind repo/ ./
# Sanity probe: the identifiers the patches add must not exist at the base commit.
RUN grep -rlwF --include='*.rs' \
        -e parse_header \
        -e MAX_DEPTH \
        -e HeaderError \
        . ; \
    test $? -eq 1 || { echo "cargorewind probe failed: found at base (files above)" >&2; exit 1; }
# Cargo.lock is committed at the base commit: fetch exactly those versions.
RUN cargo fetch --locked
# Warm build: compile dependencies and every test target once at base.
RUN cargo test --no-run
# Recipe hash: sha256 of the canonical recipe JSON (recipe.json); the cache key.
LABEL cargorewind.recipe=25d1c975b6a4664fbe27fb8e5488b50f6b37b47dbd43937e6ad57e5388cb1ec0
