# Generated by cargorewind: environment at base commit 89abcdef0123456789abcdef0123456789abcdef.
FROM rust:1.98.1-slim@sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
LABEL project=cargorewind \
      cargorewind.base-commit=89abcdef0123456789abcdef0123456789abcdef \
      cargorewind.toolchain=nightly-2020-01-01
ENV CARGO_BUILD_JOBS=2 \
    CARGO_INCREMENTAL=0 \
    CARGO_TERM_COLOR=never \
    CARGO_TARGET_DIR=/home/rewind/target
# Dated channel nightly-2020-01-01: installed with rustup on the pinned stable image.
RUN rustup toolchain install nightly-2020-01-01 --profile minimal --component rustfmt
# Pin the chosen toolchain; rustup would otherwise follow the toolchain file.
ENV RUSTUP_TOOLCHAIN=nightly-2020-01-01
RUN useradd --create-home --uid 10001 rewind
USER rewind
WORKDIR /home/rewind/repo
COPY --chown=rewind:rewind repo/ ./
# Cargo.lock is committed at the base commit: fetch exactly those versions.
RUN cargo fetch --locked
# Warm build: compile dependencies and every test target once at base.
RUN cargo test --no-run
# Recipe hash: sha256 of the canonical recipe JSON (recipe.json); the cache key.
LABEL cargorewind.recipe=b01fe4ae776fae912adfaae4b321cdddd81e9a4167aefbf25bef655297fd0432
