# Generated by cargorewind: environment at base commit abcdef0.
FROM rust:1.38.0-slim@sha256:0000000000000000000000000000000000000000000000000000000000000000
LABEL project=cargorewind \
      cargorewind.base-commit=abcdef0 \
      cargorewind.toolchain=1.38.0
ENV CARGO_BUILD_JOBS=2 \
    CARGO_INCREMENTAL=0 \
    CARGO_TERM_COLOR=never \
    CARGO_TARGET_DIR=/home/rewind/target
RUN useradd --create-home --uid 10001 rewind
USER rewind
WORKDIR /home/rewind/repo
COPY --chown=rewind:rewind repo/ ./
# No Cargo.lock at the base commit and no crates.io dependencies, so there is
# nothing to bound by the commit date: cargo writes the lockfile here.
RUN cargo generate-lockfile
# Vendor every dependency and point cargo at the copies; tests run --offline.
RUN mkdir -p /home/rewind/.cargo \
    && cargo vendor --locked /home/rewind/vendor > /home/rewind/.cargo/config
ENV CARGO_NET_OFFLINE=true
# Warm build: compile dependencies and every test target once at base.
RUN cargo test --no-run --offline
# Recipe hash: sha256 of the canonical recipe JSON (recipe.json); the cache key.
LABEL cargorewind.recipe=ee9811bb13b1ed66aa2ca9b8090281216bebbeb8e535b2439e9a7742059a4eab
