from __future__ import annotations

import pytest

from cargorewind.lockfile import (
    READ_MINIMUM,
    LockedPackage,
    LockfileError,
    format_version,
    parse_lockfile,
)

REGISTRY = "registry+https://github.com/rust-lang/crates.io-index"

V1 = f"""\
[[package]]
name = "demo"
version = "0.1.0"
dependencies = [
 "either 1.9.0 ({REGISTRY})",
]

[[package]]
name = "either"
version = "1.9.0"
source = "{REGISTRY}"

[metadata]
"checksum either 1.9.0 ({REGISTRY})" = "a26ae43d"
"""

V1_ROOT = f"""\
[root]
name = "old"
version = "0.1.0"
dependencies = [
 "libc 0.2.20 ({REGISTRY})",
]

[[package]]
name = "libc"
version = "0.2.20"
source = "{REGISTRY}"
"""

V2 = f"""\
[[package]]
name = "demo"
version = "0.1.0"
dependencies = [
 "either",
 "rand 0.7.3",
 "rand 0.8.5",
]

[[package]]
name = "either"
version = "1.9.0"
source = "{REGISTRY}"
checksum = "a26ae43d7bcc3b814de94796a5e736d4029efb0ee900c12e2d54c993ad1a1e07"

[[package]]
name = "rand"
version = "0.7.3"
source = "{REGISTRY}"
checksum = "00"

[[package]]
name = "rand"
version = "0.8.5"
source = "{REGISTRY}"
checksum = "01"
dependencies = [
 "either",
]
"""


@pytest.mark.parametrize(
    ("text", "version"),
    [
        (V1, 1),
        (V1_ROOT, 1),
        (V2, 2),
        ("version = 3\n" + V2, 3),
        ("# This file is automatically @generated by Cargo.\nversion = 4\n", 4),
        ('[[package]]\nname = "only"\nversion = "0.1.0"\n', 1),
        ("", 1),
    ],
)
def test_format_versions(text: str, version: int) -> None:
    assert format_version(text) == version


def test_read_minimum_follows_the_release_notes() -> None:
    assert READ_MINIMUM == {1: None, 2: (1, 41, 0), 3: (1, 53, 0), 4: (1, 78, 0)}


@pytest.mark.parametrize(
    ("text", "message"),
    [
        ("version = 5\n", "unknown Cargo.lock format version 5"),
        ('version = "3"\n', "unknown Cargo.lock format version '3'"),
        ("[[package]\n", "not valid TOML"),
        ('[[package]]\nname = "x"\n', "without a name or version"),
    ],
)
def test_bad_lockfiles(text: str, message: str) -> None:
    with pytest.raises(LockfileError, match=message):
        parse_lockfile(text)


def test_v1_long_form_dependencies_resolve() -> None:
    lock = parse_lockfile(V1)
    demo, either = lock.packages
    assert demo.source is None and not demo.from_crates_io
    assert either.from_crates_io and either.spec == "either:1.9.0"
    assert lock.resolve(demo.dependencies[0]) == either
    assert lock.dependents(either) == [demo]
    assert lock.registry_packages() == [either]
    root = parse_lockfile(V1_ROOT)
    assert [str(p) for p in root.packages] == ["old 0.1.0", "libc 0.2.20"]
    assert root.dependents(root.packages[1]) == [root.packages[0]]


def test_v2_short_forms_and_duplicate_names() -> None:
    lock = parse_lockfile(V2)
    rand7 = lock.find("rand", "0.7.3")
    rand8 = lock.find("rand", "0.8.5")
    either = lock.find("either", "1.9.0")
    assert rand7 is not None and rand8 is not None and either is not None
    assert lock.resolve("rand 0.7.3") == rand7
    assert lock.resolve("rand") is None  # ambiguous without a version
    assert lock.resolve("missing") is None
    assert lock.resolve("") is None
    assert lock.resolve(f"either 1.9.0 ({REGISTRY})") == either
    assert lock.resolve("either 1.9.0 (git+https://example.com/either)") is None
    assert [p.name for p in lock.dependents(either)] == ["demo", "rand"]
    assert lock.find("rand", "0.1.0") is None
    assert LockedPackage("x", "1.0.0", None).key == ("x", "1.0.0", None)
