"""Render the environment Dockerfile for one base commit."""

from __future__ import annotations

from dataclasses import dataclass

PROJECT_LABEL = "project=cargorewind"
CONTAINER_USER = "rewind"
CONTAINER_UID = 10001
REPO_DIR = f"/home/{CONTAINER_USER}/repo"
TARGET_DIR = f"/home/{CONTAINER_USER}/target"
TEST_COMMAND: tuple[str, ...] = ("cargo", "test", "--no-fail-fast")


@dataclass(frozen=True)
class Recipe:
    """Everything the Dockerfile depends on; equal recipes render equal files."""

    image: str
    toolchain: str
    base_commit: str
    has_lockfile: bool


def render_dockerfile(recipe: Recipe) -> str:
    if recipe.has_lockfile:
        deps = [
            "# Cargo.lock is committed at the base commit: fetch exactly those versions.",
            "RUN cargo fetch --locked",
        ]
    else:
        deps = [
            "# No Cargo.lock at the base commit: resolve one now. The resolution is not",
            "# yet bounded by the commit date (see PLAN.md, slice 3).",
            "RUN cargo generate-lockfile",
        ]
    lines = [
        f"# Generated by cargorewind: environment at base commit {recipe.base_commit}.",
        f"FROM {recipe.image}",
        f"LABEL {PROJECT_LABEL} \\",
        f"      cargorewind.base-commit={recipe.base_commit} \\",
        f"      cargorewind.toolchain={recipe.toolchain}",
        "ENV CARGO_BUILD_JOBS=2 \\",
        "    CARGO_INCREMENTAL=0 \\",
        "    CARGO_TERM_COLOR=never \\",
        f"    CARGO_TARGET_DIR={TARGET_DIR}",
        f"RUN useradd --create-home --uid {CONTAINER_UID} {CONTAINER_USER}",
        f"USER {CONTAINER_USER}",
        f"WORKDIR {REPO_DIR}",
        f"COPY --chown={CONTAINER_USER}:{CONTAINER_USER} repo/ ./",
        *deps,
        "# Warm build: compile dependencies and every test target once at base.",
        "RUN cargo test --no-run",
        "",
    ]
    return "\n".join(lines)
