"""Render the environment Dockerfile from a typed, hashable ``Recipe``.

The recipe holds everything the image depends on: the digest-pinned base image, the
toolchain and what rustup adds to it, the base commit, the dependency strategy (and the
sha256 of a lockfile cargorewind wrote), vendoring, the identifiers of the sanity probe
and the commands. Rendering is a pure function of it, so equal recipes give
byte-identical Dockerfiles. The recipe hash is the sha256 of its canonical JSON (sorted
keys, no whitespace, ASCII only); it is the build cache key, the image tag and the
``cargorewind.recipe`` label of the image.

Every field that reaches a Dockerfile line is validated with ``fullmatch`` when the
recipe is created, so no value can carry a newline or shell syntax into the file.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, fields
from enum import StrEnum
from typing import Any

PROJECT_LABEL = "project=cargorewind"
RECIPE_LABEL = "cargorewind.recipe"
RECIPE_SCHEMA = 1
CONTAINER_USER = "rewind"
CONTAINER_UID = 10001
HOME_DIR = f"/home/{CONTAINER_USER}"
REPO_DIR = f"{HOME_DIR}/repo"
TARGET_DIR = f"{HOME_DIR}/target"
VENDOR_DIR = f"{HOME_DIR}/vendor"
TOOLCHAIN_STAGE = "toolchain"
TEST_COMMAND: tuple[str, ...] = ("cargo", "test", "--no-fail-fast")
WARM_COMMAND: tuple[str, ...] = ("cargo", "test", "--no-run")
PROBE_GLOB = "*.rs"
PROBE_EXIT_CODE = 97  # a stage whose checkout lacks a probe identifier exits with this
PROBE_MARKER = "cargorewind probe failed:"

_IMAGE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._/:-]*@sha256:[0-9a-f]{64}")
_TOOLCHAIN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
_NAME = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]*")
_COMMIT = re.compile(r"[0-9a-f]{4,64}")
_SHA256 = re.compile(r"[0-9a-f]{64}")
_CUTOFF = re.compile(r"[0-9A-Za-z:+.-]*")
_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_WORD = re.compile(r"[A-Za-z0-9_.:=/+-]+")
CARGO_CONFIGS = ("config", "config.toml")
PROFILES = ("minimal", "default", "complete")


class LockStrategy(StrEnum):
    COMMITTED = "committed"  # Cargo.lock at the base commit: cargo fetch --locked
    GENERATED = "generated"  # no crates.io dependencies: nothing to bound by date
    BOUNDED = "date-bounded"  # generated by the pin loop, copied in, then fetched


class RecipeError(ValueError):
    """A recipe field that must not reach a Dockerfile line."""


def stage_test_command(vendor: bool) -> tuple[str, ...]:
    """The test command of every stage run; vendored environments add ``--offline``."""
    return (*TEST_COMMAND, "--offline") if vendor else TEST_COMMAND


def _check(field_name: str, value: str, pattern: re.Pattern[str]) -> None:
    if pattern.fullmatch(value) is None:
        raise RecipeError(f"recipe {field_name} {value!r} is not allowed in a Dockerfile")


@dataclass(frozen=True)
class Recipe:
    """Everything the image depends on; equal recipes render equal Dockerfiles."""

    image: str
    toolchain: str
    base_commit: str
    lock: LockStrategy = LockStrategy.COMMITTED
    install_toolchain: bool = False  # a dated channel installed with rustup
    components: tuple[str, ...] = ()
    targets: tuple[str, ...] = ()
    profile: str | None = None
    pin_toolchain: bool = False  # ENV RUSTUP_TOOLCHAIN, so toolchain files are ignored
    cutoff: str = ""  # the date bound of a generated lockfile, for the comment
    vendor: bool = False  # cargo vendor, source replacement, offline builds
    cargo_config: str = "config.toml"  # "config" for cargo before 1.39
    lockfile_sha256: str = ""  # the Cargo.lock cargorewind wrote into the context
    probes: tuple[str, ...] = ()  # identifiers that must not exist at the base commit
    warm_command: tuple[str, ...] = ()  # default: cargo test --no-run [--offline]
    test_command: tuple[str, ...] = ()  # default: cargo test --no-fail-fast [--offline]

    def __post_init__(self) -> None:
        offline = ("--offline",) if self.vendor else ()
        if not self.warm_command:
            object.__setattr__(self, "warm_command", (*WARM_COMMAND, *offline))
        if not self.test_command:
            object.__setattr__(self, "test_command", stage_test_command(self.vendor))
        try:
            object.__setattr__(self, "lock", LockStrategy(self.lock))
        except ValueError:
            raise RecipeError(f"recipe lock {self.lock!r} is not a lock strategy") from None
        self._validate()

    def _validate(self) -> None:
        _check("image", self.image, _IMAGE)
        _check("toolchain", self.toolchain, _TOOLCHAIN)
        _check("base_commit", self.base_commit, _COMMIT)
        for name in (*self.components, *self.targets):
            _check("component or target", name, _NAME)
        if self.profile is not None and self.profile not in PROFILES:
            raise RecipeError(f"recipe profile {self.profile!r} is not a rustup profile")
        _check("cutoff", self.cutoff, _CUTOFF)
        if self.cargo_config not in CARGO_CONFIGS:
            raise RecipeError(f"recipe cargo_config {self.cargo_config!r} is not a cargo config")
        if self.lockfile_sha256:
            _check("lockfile_sha256", self.lockfile_sha256, _SHA256)
            if self.lock is not LockStrategy.BOUNDED:
                raise RecipeError("recipe lockfile_sha256 is only set for a date-bounded lockfile")
        for word in self.probes:
            _check("probe", word, _IDENTIFIER)
        if len(set(self.probes)) != len(self.probes):
            raise RecipeError("recipe probes must be unique")
        for word in (*self.warm_command, *self.test_command):
            _check("command word", word, _WORD)

    def as_dict(self) -> dict[str, Any]:
        """The recipe as JSON data (tuples become lists), with its schema version."""
        data: dict[str, Any] = {"schema": RECIPE_SCHEMA}
        for spec in fields(self):
            value = getattr(self, spec.name)
            if isinstance(value, tuple):
                value = list(value)
            elif isinstance(value, LockStrategy):
                value = value.value
            data[spec.name] = value
        return data

    def canonical_json(self) -> str:
        """Sorted keys, no whitespace, ASCII only: the bytes the hash is taken over."""
        return json.dumps(self.as_dict(), sort_keys=True, separators=(",", ":"), ensure_ascii=True)

    @property
    def hash(self) -> str:
        return hashlib.sha256(self.canonical_json().encode()).hexdigest()

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Recipe:
        """Read a recipe written by ``as_dict`` (for example ``recipe.json``)."""
        if data.get("schema") != RECIPE_SCHEMA:
            raise RecipeError(f"unsupported recipe schema {data.get('schema')!r}")
        known = {spec.name for spec in fields(cls)}
        unknown = sorted(set(data) - known - {"schema", "hash"})
        if unknown:
            raise RecipeError(f"unknown recipe fields: {', '.join(unknown)}")
        values: dict[str, Any] = {
            k: tuple(v) if isinstance(v, list) else v for k, v in data.items() if k in known
        }
        try:
            return cls(**values)
        except TypeError as exc:
            raise RecipeError(f"incomplete recipe: {exc}") from exc

    def document(self) -> dict[str, Any]:
        """The recipe.json document: the recipe plus its hash."""
        return {**self.as_dict(), "hash": self.hash}


def _toolchain_lines(recipe: Recipe) -> list[str]:
    """Root-level rustup steps; empty for a plain stable image without a toolchain file."""
    name = recipe.toolchain
    lines: list[str] = []
    if recipe.install_toolchain:
        flags = [f"--profile {recipe.profile or 'minimal'}"]
        flags += [f"--component {c}" for c in recipe.components]
        flags += [f"--target {t}" for t in recipe.targets]
        lines += [
            f"# Dated channel {name}: installed with rustup on the pinned stable image.",
            f"RUN rustup toolchain install {name} {' '.join(flags)}",
        ]
    else:
        steps = []
        if recipe.components:
            steps.append(f"rustup component add --toolchain {name} {' '.join(recipe.components)}")
        if recipe.targets:
            steps.append(f"rustup target add --toolchain {name} {' '.join(recipe.targets)}")
        if steps:
            lines += [
                "# Components and targets the toolchain file asks for.",
                "RUN " + " \\\n    && ".join(steps),
            ]
    if recipe.pin_toolchain or recipe.install_toolchain:
        lines += [
            "# Pin the chosen toolchain; rustup would otherwise follow the toolchain file.",
            f"ENV RUSTUP_TOOLCHAIN={name}",
        ]
    return lines


def probe_lines(probes: tuple[str, ...]) -> list[str]:
    """The sanity probe: none of ``probes`` may occur as a word in a ``*.rs`` file.

    ``grep`` exits 1 only when nothing matched; a match (0) or an error (2) fails the
    build, and the matching files are printed to the build log.
    """
    if not probes:
        return []
    words = [f"        -e {word} \\" for word in probes]
    return [
        "# Sanity probe: the identifiers the patches add must not exist at the base commit.",
        f"RUN grep -rlwF --include='{PROBE_GLOB}' \\",
        *words,
        "        . ; \\",
        f'    test $? -eq 1 || {{ echo "{PROBE_MARKER} found at base (files above)" >&2; '
        "exit 1; }",
    ]


def _dependency_lines(recipe: Recipe) -> list[str]:
    if recipe.lock is LockStrategy.COMMITTED:
        lines = [
            "# Cargo.lock is committed at the base commit: fetch exactly those versions.",
            "RUN cargo fetch --locked",
        ]
    elif recipe.lock is LockStrategy.GENERATED:
        lines = [
            "# No Cargo.lock at the base commit and no crates.io dependencies, so there is",
            "# nothing to bound by the commit date: cargo writes the lockfile here.",
            "RUN cargo generate-lockfile",
        ]
    else:
        lines = [
            "# Cargo.lock written by cargorewind: every crates.io package was published",
            f"# before {recipe.cutoff} (see lock.json).",
            f"COPY --chown={CONTAINER_USER}:{CONTAINER_USER} Cargo.lock ./",
            "RUN cargo fetch --locked",
        ]
    if recipe.vendor:
        config = f"{HOME_DIR}/.cargo/{recipe.cargo_config}"
        lines += [
            "# Vendor every dependency and point cargo at the copies; tests run --offline.",
            f"RUN mkdir -p {HOME_DIR}/.cargo \\",
            f"    && cargo vendor --locked {VENDOR_DIR} > {config}",
            "ENV CARGO_NET_OFFLINE=true",
        ]
    return lines


def _stage_lines(recipe: Recipe) -> list[str]:
    """The first stage: base image, labels, environment, rustup, user and checkout."""
    bounded = recipe.lock is LockStrategy.BOUNDED
    return [
        f"# Generated by cargorewind: environment at base commit {recipe.base_commit}.",
        f"FROM {recipe.image}" + (f" AS {TOOLCHAIN_STAGE}" if bounded else ""),
        f"LABEL {PROJECT_LABEL} \\",
        f"      cargorewind.base-commit={recipe.base_commit} \\",
        f"      cargorewind.toolchain={recipe.toolchain}",
        "ENV CARGO_BUILD_JOBS=2 \\",
        "    CARGO_INCREMENTAL=0 \\",
        "    CARGO_TERM_COLOR=never \\",
        f"    CARGO_TARGET_DIR={TARGET_DIR}",
        *_toolchain_lines(recipe),
        f"RUN useradd --create-home --uid {CONTAINER_UID} {CONTAINER_USER}",
        f"USER {CONTAINER_USER}",
        f"WORKDIR {REPO_DIR}",
        f"COPY --chown={CONTAINER_USER}:{CONTAINER_USER} repo/ ./",
    ]


def render_toolchain_stage(recipe: Recipe) -> str:
    """Only the ``toolchain`` stage of a date-bounded recipe: what the pin loop runs in.

    It holds neither the probe nor the recipe label, so it does not depend on the
    lockfile the pin loop is about to write.
    """
    if recipe.lock is not LockStrategy.BOUNDED:
        raise RecipeError("only a date-bounded recipe has a toolchain stage")
    return "\n".join([*_stage_lines(recipe), ""])


def render_dockerfile(recipe: Recipe) -> str:
    """The environment Dockerfile. A date-bounded lockfile needs two stages: the pin loop
    runs cargo in the ``toolchain`` stage, and the final stage copies its lockfile in."""
    bounded = recipe.lock is LockStrategy.BOUNDED
    lines = [
        *_stage_lines(recipe),
        *(["", f"FROM {TOOLCHAIN_STAGE}"] if bounded else []),
        *probe_lines(recipe.probes),
        *_dependency_lines(recipe),
        "# Warm build: compile dependencies and every test target once at base.",
        "RUN " + " ".join(recipe.warm_command),
        "# Recipe hash: sha256 of the canonical recipe JSON (recipe.json); the cache key.",
        f"LABEL {RECIPE_LABEL}={recipe.hash}",
        "",
    ]
    return "\n".join(lines)
