"""Render the environment Dockerfile for one base commit."""

from __future__ import annotations

from dataclasses import dataclass

PROJECT_LABEL = "project=cargorewind"
CONTAINER_USER = "rewind"
CONTAINER_UID = 10001
REPO_DIR = f"/home/{CONTAINER_USER}/repo"
TARGET_DIR = f"/home/{CONTAINER_USER}/target"
TEST_COMMAND: tuple[str, ...] = ("cargo", "test", "--no-fail-fast")


@dataclass(frozen=True)
class Recipe:
    """Everything the Dockerfile depends on; equal recipes render equal files."""

    image: str
    toolchain: str
    base_commit: str
    has_lockfile: bool
    install_toolchain: bool = False  # a dated channel installed with rustup
    components: tuple[str, ...] = ()
    targets: tuple[str, ...] = ()
    profile: str | None = None
    pin_toolchain: bool = False  # ENV RUSTUP_TOOLCHAIN, so toolchain files are ignored


def _toolchain_lines(recipe: Recipe) -> list[str]:
    """Root-level rustup steps; empty for a plain stable image without a toolchain file."""
    name = recipe.toolchain
    lines: list[str] = []
    if recipe.install_toolchain:
        flags = [f"--profile {recipe.profile or 'minimal'}"]
        flags += [f"--component {c}" for c in recipe.components]
        flags += [f"--target {t}" for t in recipe.targets]
        lines += [
            f"# Dated channel {name}: installed with rustup on the pinned stable image.",
            f"RUN rustup toolchain install {name} {' '.join(flags)}",
        ]
    else:
        steps = []
        if recipe.components:
            steps.append(f"rustup component add --toolchain {name} {' '.join(recipe.components)}")
        if recipe.targets:
            steps.append(f"rustup target add --toolchain {name} {' '.join(recipe.targets)}")
        if steps:
            lines += [
                "# Components and targets the toolchain file asks for.",
                "RUN " + " \\\n    && ".join(steps),
            ]
    if recipe.pin_toolchain or recipe.install_toolchain:
        lines += [
            "# Pin the chosen toolchain; rustup would otherwise follow the toolchain file.",
            f"ENV RUSTUP_TOOLCHAIN={name}",
        ]
    return lines


def render_dockerfile(recipe: Recipe) -> str:
    if recipe.has_lockfile:
        deps = [
            "# Cargo.lock is committed at the base commit: fetch exactly those versions.",
            "RUN cargo fetch --locked",
        ]
    else:
        deps = [
            "# No Cargo.lock at the base commit: resolve one now. The resolution is not",
            "# yet bounded by the commit date (see PLAN.md, slice 3).",
            "RUN cargo generate-lockfile",
        ]
    lines = [
        f"# Generated by cargorewind: environment at base commit {recipe.base_commit}.",
        f"FROM {recipe.image}",
        f"LABEL {PROJECT_LABEL} \\",
        f"      cargorewind.base-commit={recipe.base_commit} \\",
        f"      cargorewind.toolchain={recipe.toolchain}",
        "ENV CARGO_BUILD_JOBS=2 \\",
        "    CARGO_INCREMENTAL=0 \\",
        "    CARGO_TERM_COLOR=never \\",
        f"    CARGO_TARGET_DIR={TARGET_DIR}",
        *_toolchain_lines(recipe),
        f"RUN useradd --create-home --uid {CONTAINER_UID} {CONTAINER_USER}",
        f"USER {CONTAINER_USER}",
        f"WORKDIR {REPO_DIR}",
        f"COPY --chown={CONTAINER_USER}:{CONTAINER_USER} repo/ ./",
        *deps,
        "# Warm build: compile dependencies and every test target once at base.",
        "RUN cargo test --no-run",
        "",
    ]
    return "\n".join(lines)
